### ISSUE TITLE
[improvement]: Possible issue in app_amd.c

### ISSUE THREAD

**Issue by moha-abdi** [asterisk/asterisk#598]
### Improvement Description

In app_amd.c, it looks like the initialsilence will never be detected, as in lines 370, 371, and 375, it shows that the silence duration is reset in each duration, which means the initial silence will never be detected. There is no part of the code showing that the initialsilence is incremented which means it will always be a small value. Please take a look at this.

**Comment by InterLinked1** [comment]
The line numbers you provided don't seem to quite line up, but are you referring to this one? https://github.com/asterisk/asterisk/blob/master/apps/app_amd.c#L372

The DSP itself is responsible for accumulation so we shouldn't be incrementing in the application, the value is set by the core DSP function. Is there another issue you're seeing here?

**Comment by moha-abdi** [comment]
Yes that is the one I was reffetring.
We pass the DSP a pointer to dspsilence [here](https://github.com/asterisk/asterisk/blob/master/apps/app_amd.c#L372). Since dspsilence is set to zero each time, this means the DSP will only accumulate the current frame's calculated silence duration to dspsilence (which is 0), as shown [here](https://github.com/asterisk/asterisk/blob/master/main/dsp.c#L1248). Consequently, in each iteration, dspsilence is actually reset to zero, except if the type is not AST_FRAME_VOICE, which is not the case for this issue.

The main question is how will this [line ](https://github.com/asterisk/asterisk/blob/master/apps/app_amd.c#L390)ever be true, if the default value for initialSilence was 2.5 seconds and the the silence duration variable only contains the length for the current frame, as in [here](https://github.com/asterisk/asterisk/blob/master/main/dsp.c#L1248)

**Comment by InterLinked1** [comment]
> Yes that is the one I was reffetring. We pass the DSP a pointer to dspsilence [here](https://github.com/asterisk/asterisk/blob/master/apps/app_amd.c#L372). Since dspsilence is set to zero each time, this means the DSP will only accumulate the current frame's calculated silence duration to dspsilence (which is 0), as shown [here]

I'm not following... dsp->totalsilence does accumulate internally and this just sets it to whatever that currently is.

Technically the initialization is unnecessary, since that should always be assigned as it's non-NULL. But I don't think the initialization does any harm.

(https://github.com/asterisk/asterisk/blob/master/main/dsp.c#L1248). Consequently, in each iteration, dspsilence is actually reset to zero, except if the type is not AST_FRAME_VOICE, which is not the case for this issue.
> 
> The main question is how will this [line ](https://github.com/asterisk/asterisk/blob/master/apps/app_amd.c#L390)ever be true, if the default value for initialSilence was 2.5 seconds and the the silence duration variable only contains the length for the current frame, as in [here](https://github.com/asterisk/asterisk/blob/master/main/dsp.c#L1248)

I guess I disagree that it's for the current frame... I might have missed something but that's what a quick scan of the code in dsp.c suggests. The link you linked shows an increment, nore a replace. The dsp is stateful and keeps track of things between frames. Also, the logic does work for existing use cases.

**Comment by moha-abdi** [comment]
> 
> I guess I disagree that it's for the current frame... I might have missed something but that's what a quick scan of the code in dsp.c suggests. The link you linked shows an increment, nore a replace. The dsp is stateful and keeps track of things between frames. Also, the logic does work for existing use cases.

Thanks for the explanation this looks quite confincing to me, I oversaw this [line ](https://github.com/asterisk/asterisk/blob/master/main/dsp.c#L1287)which means its working normally, and I am sorry for the time that this cost you. Good luck.
