### ISSUE TITLE
[improvement]: Allow for attended transfer to complete while in early state

### ISSUE THREAD

**Issue by jmordica** [asterisk/asterisk#641]
### Improvement Description

Running in Asterisk 20.1.0

I'm having to use this PJSIP patch:
```
--- res/res_pjsip/config_system.c
+++ res/res_pjsip/config_system.c
@@ -87,6 +87,7 @@ static void *system_alloc(const char *name)
 
 static int system_apply(const struct ast_sorcery *sorcery, void *obj)
 {
+  pjsip_cfg()->endpt.accept_replace_in_early_state = PJ_TRUE;
    struct system_config *system = obj;
    int min_timerb;
```

In order to allow attended transfer to complete. Meaning, if the person transferring the call hangs up or completes the transfer before the party answers, the call is still successfully transferred.

I believe this is actually causing a bug in asterisk when this is mixed with external_replaces (transferring to another asterisk server).

I'm looking to see if:
1. Can the enhancement be added to allow early state transfers to complete.
2. Could this patch be causing an a locking issue and maybe it's not the best way to solve this problem.

Thanks.

**Comment by jcolp** [comment]
The change can't be added as-is, it won't build in dev mode. It also needs to be optional and default to off, as well as have test coverage. It also needs to be researched what version of PJSIP it is present in, and appropriate check added to configure.

There is insufficient information to be able to comment on a locking issue. Is it possible though? Sure. Other code may not have been written for the scenario in question and have assumptions otherwise.

**Comment by asteriskteam** [comment]
This issue has been marked stale because it has been open 7 days with no feedback. Please provide feedback within 7 days or this issue will be closed.

**Comment by asteriskteam** [comment]
This issue has been closed because it has been open 14 days with no feedback.
