### ISSUE TITLE
[new-feature]: ARI channel tone detect events.

### ISSUE THREAD

**Issue by gibbz00** [asterisk/asterisk#811]
### Feature Description

At work we need to listen to a 1400Hz special information tone for conference call detection as specified in [Swedish tones in public communications network](https://its.se/wp-content/uploads/its-apg-31-utgava-1-faststalld-2023-11-09.pdf).

We would ideally like to register tone detection event listening on a given channel, for it to then be ready when `/ari/bridges/<id>/addChannel` is requested.

I read some [AstriDevCon notes](https://docs.asterisk.org/Development/Roadmap/AstriDevCon-2015/#sean-mccord) dating all the way back to 2015 where such a feature is mentioned as a nice to have. Has anyone looked into it since then? Feels very much like a non-trivial task given that 9 years have now gone by. 

I would be more than happy to send in a PR for this, but I'm afraid all of this is a bit over my head given that both C and Asterisk are completely new to me. I've begun looking at the source code and here's what I've deduced so far:

* Sending events over WS from subscribed stasis messages seems pretty straight forward. 

* Register event listening by translating an HTTP request into a `res_tonetetect::detect_write` call might be doable.

* But how should events be created?  In `channel.c`'s `__ast_read` by somehow calling `res_tonedetect::detect_read`?

Am I on the right path, or is another way recommended? Feed-back is greatly appreciated.

**Comment by jcolp** [comment]
The issue tracker is really for issues, not for discussions such as this. In the future please use the asterisk-dev mailing list: https://groups.io/g/asterisk-dev

The res_tonedetect module already shows how to passively listen for tones, as it does it in the TONE_DETECT dialplan function. This function uses an audiohook which allows the dialplan function implementation to receive the audio from the channel, it then passes it to the DSP to do analysis, and acts on it. The only difference is that in your case you would want to raise an event. This is done by publishing a stasis message on the channel, with a type that has a converter into JSON. An example of this that exists already would be TALK_DETECT. No ARI modification was needed to support that because it is a dialplan function that can be placed on the channel using the /variable route of the channel. It then passively detects when speaking is happening, and raises an event over ARI.

**Comment by gibbz00** [comment]
Hii, thanks for the quick response.

> The issue tracker is really for issues, not for discussions such as this. In the future please use the asterisk-dev mailing list: https://groups.io/g/asterisk-dev

Apologies. Now I know for next time.

I was aware of TALK_DETECT but not the `/variable` endpoint. Helped tremendously, thank you!!
